### ISSUE TITLE
Variadic and convenient `select` and `join`

### ISSUE THREAD

**Issue by aturon** [rustasync/team#2]
Rather than have some fixed number of `select`/`join` combinators, we want to explore a variadic, macro-based approach.

**Comment by cramertj** [comment]
In addition to `select`/`join`, we'll want a variadic macro for pinning a number of arguments into a single location. This could be used in combination with an impl of `Future` and `Stream` for `&pin T where T: AsyncResult` in order to allow `select` and `join` to not bake in looping (which would be needed if the `select` or `join` itself performed the pinning).

I'm imagining usage that looks something like this:

```rust
let x = async { ... };
let y = async { ... };
let z = async { ... };
let timeout = 5.seconds().after_now();
pin!((x, y, z) in {
    let mut state = 0;
    while state < 5 {
        select! {
            (x as xres) => state += xres?,
            (y as yres) => state += yres?,
            (z as zres) => state += zres?,
            (timeout as _) => bail!("oh noez! timeout"),
        }
    }
})
```

cc @ralfjung Are you able to prove that `&mut &pin T` allows calling `&pin` methods on `T`? This seems similar to the `&&pin T` case that I thought was reasonable, but where you disagreed IIRC. I think the issue is that you're viewing the `&mut` or `&` as "giving up" the privileges of `&pin`, right? We should make sure to resolve this.

**Comment by RalfJung** [comment]
> cc @RalfJung Are you able to prove that &mut &pin T allows calling &pin methods on T? 

Isn't that just calling `borrow`?

**Comment by cramertj** [comment]
@ralfjung Yes, I'm just trying to sort out why that is allowed, but `&&pin` doesn't work as I'd expect under your model.
