### ISSUE TITLE
Proposal: adopt "async first" policy

### ISSUE THREAD

**Issue by jsgf** [rustasync/team#32]
# Background

The sync/async distinction effectively splits the ecosystem.

If one is writing an application, one is immediately restricted by the set of crates you can use to the one that matches your app. Ideally there's an existing crate which has a complete API, works well, is well tested and actively maintained. But in practice there's often "the sync one" or "the async one", and even if both exist they are maintained by different people, and are very unlike each other at least at the API level.

Worst case, the crate just doesn't exist for the model you want, so you either need to write your own, or adapt an existing crate with the wrong model to your crate.

As we move towards async/await, the distinction between sync and async programs becomes syntactically less distinct, which means the overhead for either always using async or converting sync to async is lower.

In this world, having a complete split between the sync and async ecosystems will become an acute problem.

# Proposal

We promote the idea that all network protocol crates be written in the async style first, and then provide sync shims/adapters for sync users. This is because async code is strictly more general - you can easily adapt it to sync by putting it in its own little tokio runtime environment.

On the other hand, sync code can't be easily adapted to async, except by decoupling it into threads. This is very much more expensive, and may preclude many uses (ie, its only really viable for small-scale implementations).

The main downside is that async code is a lot harder to write and debug at the moment. But the Rust community is putting lots of effort into improving this, so the overall goal aligns with this specific proposal.

**Comment by ashfordneil** [comment]
> you can easily adapt it to sync by putting it in its own little tokio  runtime environment

Having "no runtime" (or no-more-runtime-than-C, but that's a mouthful) is something that's important to some users of rust. That said, I feel like zero-cost transformations from async code to sync code could be done if we keep things generic enough (`impl<R> AsyncRead for R where R: Read` style things). If we get it zero-cost, then the async code would indeed be strictly more general as you say - and then I'm all for this.

**Comment by rolftimmermans** [comment]
Perhaps this approach also takes care of every networking related crate being called `tokio-*`? Instead maybe it's possible to label crates in crates.io as `async` or not? That would make much more sense for newbies.

**Comment by jsgf** [comment]
@ashfordneil Sync and async are duels of each other.

Sync code implicitly encodes state in terms of stack frames, and each state machine needs its own stack - the "runtime" is therefore having multiple threads which implies a lot of infrastructure.

Async code makes the state machines more explicit in various data structures, and needs an execution framework around it to drive those state machines forward. That's a lot lighter weight than having threads, with the constraint that you need to do everything within the state machine framework.

The latter is probably a lot lighter weight, and generally the preferred approach for anything that either has high performance requirements or low resource use requirements.

@rolftimmermans Agreed that things in crates.io should be consistently marked sync/async.

**Comment by ashfordneil** [comment]
@jsgf my concern is more for cases where your code does everything in serial, and is also hardware constrained. In this case, the alternative to Async isn’t threads, it’s just blocking.

**Comment by jsgf** [comment]
@ashfordneil I guess it depends on "it's just blocking" means - what's doing the blocking? What is being blocked?

**Comment by inejge** [comment]
As a data point, I wrote an [LDAP client library](https://github.com/inejge/ldap3) structured as an async core with sync adapters for blocking operations. I had the luxury of starting almost from scratch, so I could concentrate on developing the async part, and the sync API was mostly a fairly trivial wrapper around the async core. Async and sync APIs are almost identical for the majority of protocol operations, except for streaming searches and search cancellation.

The asynchronous nature of the library is pretty well hidden when using the blocking API, with the glaring exception of the connection handle (`LdapConn`) [being `!Send`](https://github.com/inejge/ldap3/issues/18) -- it uses several `Rc<RefCell<...>>` fields internally to overcome Tokio's ownership limitations. This makes the handles unusable with multithreaded connection pools, and also, although I haven't checked, with the new-style Tokio default multithreaded executor; the library was build around the original Tokio which combined the reactor and the executor in a single thread.

So far, I haven't heard from anybody who tried to use the library in an async setting, not counting myself, so I don't know whether any of the above is a dealbreaker. Anyhow, it _can_ be seen as a kind of cautionary tale: structuring the library in a certain way doesn't save it from the ecosystem changing around it.

**Comment by jsgf** [comment]
@inejge Non-Sendable futures are pretty painful these days, and are effectively unusable in the current Tokio API. They're also very contagious, since anything using them also becomes non-Sendable. We were very relieved to move away from hyper-0.11 for this reason.

**Comment by ashfordneil** [comment]
All I see being necessary for this stance to be taken without a loss of generality, so to speak, is for all Read types to impl AsyncRead (same for Write, AsyncWrite), and for a `.block()` method on a future that keeps polling it till it finishes. At which point we can combine this with #31 and start working to make the networking component of the ecosystem Async first and generic over AsyncRead / AsyncWrte. That would provide zero cost shims for sync code for free - just use a blocking IO source and call the method on the future when you’re ready.

**Comment by MajorBreakfast** [comment]
@ashfordneil Such a method exists in futures 0.1. It's called `wait`. However, it was removed in 0.2 because it was too easy to (mis)use. Now, there's the `block_on` free function.

**Comment by sfackler** [comment]
I'm in the middle of a rewrite of the tokio-postgres and postgres crates, and am currently questioning whether postgres will continue to be a separate implementation or be a blocking API over tokio-postgres. I think I do like the idea of "async first", but one thing that I think we'll want here is a "standard" runtime that all of the sync wrapper crates can share. The status quo isn't great since you'd end up with a set of reqwest threads, a set of postgres threads, etc. It could be as simple as a crate that has a lazy_static tokio Runtime?

**Comment by ashfordneil** [comment]
The sync alternative to an async api - hopefully this won’t be complex enough to require a separate crate - shouldn’t need to involve spawning threads at all. Unless parsing your protocol involves using multiple futures concurrently, polling the future returned by the async api (repeatedly) until it completes on your normal thread with synchronous IO types should suffice.

Also, having an implicit Tokio runtime behind a lazy_static wouldn’t count as running your code synchronously anyway, which still leaves us not supporting the situations where you can’t afford the overhead of tokio. 

Some caveats to the synchronous solution I discuss, though. To poll a future you need a context struct to give to it. I would recommend perhaps exporting a synchronous and single threaded executor from a module somewhere - just NOP on the wake function, and panic on the spawn function. As we expect most crates to be generic over the leaf futures / IO types given to them, the wake function won’t get called in synchronous mode. In the case where a network protocol crate requires executing multiple futures and running them in parallel, the synchronous equivalent of the code would need to be written separately. Protocols that require this, I imagine, would be incredibly rare - and complex enough that a synchronous version of the crate would likely require its own design anyway.

**Comment by ashfordneil** [comment]
If HTTP/2 requires spawning multiple concurrent tasks to work, how do synchronous HTTP/2 libraries work? (not necessarily in rust)

**Comment by sfackler** [comment]
HTTP/2 is a multiplexed protocol, so there are intrinsically expected to be multiple things going on at the same time. Which synchronous HTTP/2 libraries in particular? OkHttp spawns a thread for each HTTP2 connection.

**Comment by sfackler** [comment]
Yeah, I'd imagine there'd be an API that would allow you to either manually spawn the future and have a Cargo feature that'd provide an API to spawn it onto the default runtime for you.

**Comment by Nemo157** [comment]
Just using blocking IO won't work for turning an async library into a sync one. To take one example:

```rust
let (tx, rx) = oneshot::channel();

let (value, _) = await!(join!(rx.recv(), tx.send(5)));
```

this will work with an async channel because the `recv` will yield allowing the `send` to run first, if the channel was blocking then this would deadlock waiting for a value that can never come.

I'm not sure what the exact symptoms would be with IO types, but I have had it happen when writing an `AsyncBufRead::poll_fill_buf` implementation that failed to work with `StdIn` because of the blocking behaviour.

So the suggestions to just use a `Read`/`Write` type in place of `AsyncRead`/`AsyncWrite` I don't think will work, you _can_ use `tokio` or something internally and provide a synchronous API by just using `block_on`, but that still needs to properly utilise the wake system to work.

**Comment by ashfordneil** [comment]
Re: just use a runtime in the background / with lazy_static / etc
This isn’t actually making a synchronous wrapper around an Async library. It’s just making the Async implicit instead of explicit, and misleading API consumers. If the sync version of a crate that we offer doesn’t run like any other synchronous function (ie on the thread it was called on, blocking until completion, and without spawning up a global runtime) then we should just tell people that there isn’t a synchronous version of the library, rather than hiding the Async complexity and costs of the api. 

Re: the example with the channel 
This is essentially the same case as the multiplexing protocol, where your library is running multiple tasks in parallel. Any protocol that you could manually write a sync library for (without threading), you could also write an Async library for that doesn’t do anything concurrently. So if we prioritise the case where your protocol is serial when deciding on the standard ways to make a crate synchronous (and just block on the Async api), the sync story will stay just as good as it was before the “Async first” movement.

Re: the issue with AsyncBufRead
Can you show us the code that lead to this? Because I think unless it’s running tasks in parallel it should be solvable. 

Re: don’t think it’ll work if we just put in Read / Write types
I think it will, at this point in time. Perhaps we should find an example crate that’s Async first and generic and then just try it? @sfackler what sort of time frame do you think an Async first Postgres would happen over, could we use that as an example to try and build sync wrappers around? If not we can look into other, possibly simpler, crates to test this on.

**Comment by Nemo157** [comment]
> Re: just use a runtime in the background / with lazy_static / etc

You don't need to run the runtime in the background, you can use something like [`LocalPool`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.3/futures/executor/struct.LocalPool.html) to run even a multi-task async process on a single thread as a blocking call. If you're using `tokio` you would need an integrated reactor for the wake notifications as well, but it seems like `tokio` could provide a futures 0.3 reactor+single-threaded executor in the future.

> Re: the issue with AsyncBufRead
> Can you show us the code that lead to this? Because I think unless it’s running tasks in parallel it should be solvable.

See https://github.com/Nemo157/embrio-rs/blob/master/embrio-util/src/io/buf_reader.rs#L52 (note this is using a custom `Read` trait that is basically `AsyncRead` but with `PinMut<Self>` and an associated error type instead of using `io::Error`, that doesn't affect this example much).

The highlighted return should not be necessary, we should be able to keep looping round polling the reader until either 1. it returns `Async::Pending` or 2. it fills the buffer completely. That behaviour could be useful in cases where the reader has multiple internal buffers being written to fast enough that it's able to service another read call straight away after it finishes the last. When the reader is blocking though, instead of returning `Async::Pending` it will just block until the buffer is completely filled.

**Comment by ashfordneil** [comment]
So for a proof of concept, I wrote a _very_ minimal executor of serial futures and tested it [here](https://github.com/ashfordneil/futures_http/blob/master/examples/synchronous_and_serial.rs). The example I'm testing it on (reading a HTTP header from a TcpStream) isn't complex at all, but I am reasonably confident this approach will be able to handle anything that doesn't run concurrent futures.
