### ISSUE TITLE
Review Transport Layer Security solutions

### ISSUE THREAD

**Issue by ashfordneil** [rustasync/team#40]
There are lots of options available, we should look into answering the following questions for each of the options to a newcomer (or myself, because I personally want to know what to use)

- is this library secure + able to be trusted 
- does this library require dynamic linking against system wide libraries + how do I do that
- how do I write a docker file to build my project that uses this library
- is this library usable with {Async, no_std, etc}
- how featureful is this library (does it only do a subset of what TLS allows)
- how well designed is the api of this library (am I able to accidentally write insecure code easily using this api)

**Comment by jsgf** [comment]
We have strong requirements of our TLS libraries, mostly to do with using all corners of client cert validation. In general, the cross platform libraries seem to be insufficiently powerful - we end up needing the full OpenSSL (or equiv) API.

A platform agnostic API would be nice, but its secondary to having the right functionality even if it needs multiple implementations/conditional code.

**Comment by therealprof** [comment]
@jsgf I found `mbedTLS` to be catching up nicely.

**Comment by KizzyCode** [comment]
We should also consider to wrap existing OS'-native implementations like it's done in [`native-tls`](https://crates.io/crates/native-tls). There are two main reasons for this:
 - Better integration. E.g. under macOS most libraries do not work correctly because they cannot handle the Keychain (macOS' trust store) correctly – sometimes they do not find a valid root certificate storage, sometimes they ignore user settings (custom trust settings, system-wide enforced OCSP validation etc.)
 - Better testing. OS-TLS-stacks are heavily tested – and even there, mistakes happen. Of course we have the "Rust-advantage" if we write a native implementation, but it's still going to be pretty tough to achieve a similar level of security.

The first point might be solvable, but it would result in a whole bunch of platform-dependent code (and probably even in calling unstable APIs).
But I think the second point is the real dealbreaker here because it's a matter of trust. OpenSSL is well established and so are mbedTLS, SChannel and the Security Framework – our new Rust library is not (yet). And if there isn't an important name like Mozilla or a well known developer behind it, this may take a very very long time.

**Comment by djc** [comment]
I very much agree with @ctz. I think people use Rust in part because they believe it will be more secure in security-sensitive contexts, and the best we can do is make it easy to swap out the old and mature but often vulnerable libraries out for pure Rust implementations, so that those can mature.
